Repository softeerbootcamp-3rd/Team2-iFive, pull requests merged in 2024-02, with the labels that each got.

#2 docs: 리드미에 문서 항목 추가
  README.md
Labels: documentation

#13 Feat#1 setting
  FE/src/global.css
  FE/src/main.jsx
  FE/src/styles/color.scss
  FE/src/styles/fontStyle.scss
  FE/src/styles/global.css
  FE/src/styles/layout.scss
  FE/src/styles/util.scss
Labels: enhancement

#14 feat: 엔티티 매핑관계 연결
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/iDrop.main.iml
  .idea/uiDesigner.xml
  BE/iDrop/src/main/java/ifive/idrop/controller/init
  BE/iDrop/src/main/java/ifive/idrop/entity/Car.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Certification.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Child.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Driver.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Parent.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUp.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpInfo.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpLocation.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpSubscribe.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/Gender.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/PickUpStatus.java
  BE/iDrop/src/main/java/ifive/idrop/repository/init
  BE/iDrop/src/main/java/ifive/idrop/service/init
Labels: enhancement

#17 Feat#10 publish subscribe
  FE/package.json
  FE/src/App.jsx
  FE/src/assets/back.svg
  FE/src/components/Subscribe/TimeItem.jsx
  FE/src/components/Subscribe/TimeItem.module.scss
  FE/src/components/common/Footer/Footer.jsx
  FE/src/components/common/Footer/Footer.module.scss
  FE/src/components/common/Header/Header.jsx
  FE/src/components/common/Header/Header.module.scss
  FE/src/pages/Subscribe/Subscribe.jsx
  FE/src/pages/Subscribe/Subscribe.module.scss
  FE/src/pages/SubscribeDriverDetail.jsx
  FE/src/pages/SubscribeDrivers.jsx
  FE/src/styles/fontStyle.scss
  FE/src/styles/global.css
  FE/vite.config.js
  FE/yarn.lock
Labels: enhancement

#21 Feat#9 map publishing
  FE/.gitignore
  FE/index.html
  FE/package.json
  FE/src/App.jsx
  FE/src/Components/Common/Bottomsheet/Bottomsheet.jsx
  FE/src/Components/Common/Bottomsheet/Bottomsheet.module.scss
  FE/src/Components/Common/Bottomsheet/KidInfoBox.jsx
  FE/src/Components/Common/Bottomsheet/kidInfoBox.module.scss
  FE/src/pages/Map/Map.jsx
  FE/src/pages/Map/map.module.scss
  FE/src/styles/fontStyle.scss
  FE/vite.config.js
  FE/yarn.lock
Labels: enhancement

#22 Feat#20 publish onboarding
  FE/src/App.jsx
  FE/src/Components/Onboarding/Type.jsx
  FE/src/Components/Onboarding/Type.module.scss
  FE/src/assets/logo.svg
  FE/src/assets/truck.png
  FE/src/assets/user.svg
  FE/src/pages/Onboarding/Onboarding.jsx
  FE/src/pages/Onboarding/Onboarding.module.scss
  FE/src/styles/fontStyle.scss
Labels: enhancement

#23 Feat#16 ci
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
Labels: documentation, enhancement

#25 docs: 배포브랜치 변경
  .github/workflows/gradle.yml
Labels: fix, documentation

#27 feat: login 퍼블리싱 완료
  FE/src/App.jsx
  FE/src/pages/Login/Login.jsx
  FE/src/pages/Login/Login.module.scss
Labels: enhancement

#29 style: 바텀시트 및 아이 정보 박스 스타일 수정
  FE/src/Components/Common/Bottomsheet/Bottomsheet.jsx
  FE/src/Components/Common/Bottomsheet/Bottomsheet.module.scss
  FE/src/Components/Common/Bottomsheet/kidInfoBox.module.scss
  FE/src/pages/menu/Menu.module.scss
Labels: enhancement

#32 Feat#11 publish driver list
  FE/src/App.jsx
  FE/src/Components/DriverList/DriverItem.jsx
  FE/src/Components/DriverList/DriverItem.module.scss
  FE/src/pages/DriverList/DriverList.jsx
  FE/src/pages/DriverList/DriverList.module.scss
  FE/src/pages/SubscribeDriverDetail.jsx
  FE/src/pages/SubscribeDrivers.jsx
  FE/src/styles/fontStyle.scss
Labels: enhancement

#35 Feat#31 publish pickup payment matching
  FE/src/App.jsx
  FE/src/assets/bell.svg
  FE/src/assets/contact.svg
  FE/src/assets/credit.svg
  FE/src/components/DriverList/DriverItem.jsx
  FE/src/components/DriverList/DriverItem.module.scss
  FE/src/components/Onboarding/Type.jsx
  FE/src/components/Onboarding/Type.module.scss
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.module.scss
  FE/src/components/common/Bottomsheet/KidInfoBox.jsx
  FE/src/components/common/Bottomsheet/kidInfoBox.module.scss
  FE/src/components/common/Complete/Complete.jsx
  FE/src/components/common/Complete/Complete.module.scss
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Menu/Menu.module.scss
  FE/src/pages/Menu/menuButton.jsx
  FE/src/pages/Menu/menuButton.module.scss
  FE/src/pages/Publish/Publish.jsx
  FE/src/styles/fontStyle.scss
Labels: enhancement

#44 Feat#41 map-componentization
  FE/index.html
  FE/src/App.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/KidInfoBox.jsx
  FE/src/components/common/Map/Map.jsx
  FE/src/components/common/Map/map.module.scss
  FE/src/pages/Locate/Locate.jsx
  FE/src/pages/Map/Map.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/vite.config.js
Labels: enhancement

#47 Feat#45 pickup screen publish
  FE/src/App.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.module.scss
  FE/src/components/common/Bottomsheet/kidInfoBox.module.scss
  FE/src/pages/PickUp/PickUp.jsx
  FE/src/pages/PickUp/PickUp.module.scss
Labels: enhancement

#39 Feat#15 login
  BE/iDrop/build.gradle
  BE/iDrop/src/main/java/ifive/idrop/annotation/Login.java
  BE/iDrop/src/main/java/ifive/idrop/config/WebConfig.java
  BE/iDrop/src/main/java/ifive/idrop/controller/AuthController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/UserController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/init
  BE/iDrop/src/main/java/ifive/idrop/dto/BaseResponse.java
  BE/iDrop/src/main/java/ifive/idrop/dto/LoginRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/SignUpRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/TokenRefreshRequest.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Driver.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Parent.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpSubscribe.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/Role.java
  BE/iDrop/src/main/java/ifive/idrop/exception/CommonException.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorResponse.java
  BE/iDrop/src/main/java/ifive/idrop/exception/GlobalExceptionHandler.java
  BE/iDrop/src/main/java/ifive/idrop/filter/AuthenticateUser.java
  BE/iDrop/src/main/java/ifive/idrop/filter/JwtAuthorizationFilter.java
  BE/iDrop/src/main/java/ifive/idrop/filter/JwtFilter.java
  BE/iDrop/src/main/java/ifive/idrop/filter/VerifyUserFilter.java
  BE/iDrop/src/main/java/ifive/idrop/jwt/Jwt.java
  BE/iDrop/src/main/java/ifive/idrop/jwt/JwtProperties.java
  BE/iDrop/src/main/java/ifive/idrop/jwt/JwtProvider.java
  BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/init
  BE/iDrop/src/main/java/ifive/idrop/resolver/LoginUsersArgumentResolver.java
  BE/iDrop/src/main/java/ifive/idrop/service/UserService.java
  BE/iDrop/src/main/java/ifive/idrop/service/init
  BE/iDrop/src/main/resources/application.yml
Labels: enhancement

#53 Feat#40 path
  FE/index.html
  FE/src/App.jsx
  FE/src/components/Search/AddressFinderMap/AddressFinderMap.jsx
  FE/src/components/Search/AddressFinderMap/AddressFinderMap.module.scss
  FE/src/components/Search/AddressFinderMap/initMap.js
  FE/src/components/Search/Modal.jsx
  FE/src/components/Search/Modal.module.scss
  FE/src/components/Search/TimeItem.jsx
  FE/src/components/Search/TimeItem.module.scss
  FE/src/components/common/Footer/Footer.jsx
  FE/src/components/common/Loader/Loader.jsx
  FE/src/components/common/Loader/Loader.module.scss
  FE/src/pages/Search/Search.jsx
  FE/src/pages/Search/Search.module.scss
  FE/src/pages/Subscribe/Subscribe.jsx
  FE/src/utils/getCurrentLocation.js
Labels: enhancement

#54 Feat#6 login
  FE/src/App.jsx
  FE/src/pages/Login/Login.jsx
  FE/src/service/api.js
  FE/src/utils/auth.js
Labels: enhancement

#55 Feat#46 driver menu page
  FE/src/assets/calender.svg
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.module.scss
  FE/src/components/common/Map/Map.jsx
  FE/src/components/common/Map/map.module.scss
  FE/src/constants/constants.js
  FE/src/pages/Locate/Locate.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Menu/Menu.module.scss
  FE/src/pages/Menu/menuButton.jsx
  FE/src/pages/PickUp/PickUp.jsx
  FE/src/utils/map.js
Labels: enhancement

#56 Feat#46 driver menu page
  FE/src/components/common/Map/Map.jsx
  FE/src/constants/constants.js
  FE/src/pages/Menu/Menu.jsx
  FE/src/utils/map.js
Labels: enhancement

#52 Feat#34 location_tracking
  BE/iDrop/build.gradle
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUp.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/filter/AuthenticateUser.java
  BE/iDrop/src/main/java/ifive/idrop/util/CustomObjectMapper.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/PickUpInfoRepository.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/WebSocketConfig.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/ChildGeoLocation.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/CurrentPickUp.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/DriverGeoLocation.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
  BE/iDrop/src/main/resources/application.yml
  README.md
Labels: enhancement

#66 feat: filter를 통해 header의 origin을 필터링 하도록 수정
  BE/iDrop/src/main/java/ifive/idrop/config/WebConfig.java
  BE/iDrop/src/main/java/ifive/idrop/filter/CorsFilter.java
Labels: enhancement

#67 Feat#64 optimize map
  FE/src/components/Search/AddressFinderMap/AddressFinderMap.jsx
  FE/src/components/Search/AddressFinderMap/initMap.js
  FE/src/constants/constants.js
  FE/src/hooks/useCoords.js
  FE/src/hooks/useMap.js
  FE/src/hooks/useMarker.js
  FE/src/utils/coords.js
Labels: enhancement

#68 feat: 기사 상세정보 퍼블리싱
  FE/src/App.jsx
  FE/src/pages/DriverDetail/DriverDetail.jsx
  FE/src/pages/DriverDetail/DriverDetail.module.scss
Labels: enhancement

#69 Feat#6 login
  FE/src/App.jsx
  FE/src/constants/constants.js
  FE/src/pages/Home.jsx
  FE/src/service/api.js
  FE/src/utils/map.js
Labels: enhancement

#71 fix: login body key 변경
  FE/src/service/api.js
Labels: fix

#77 Feat#76 table change
  BE/iDrop/.gitignore
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUp.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpInfo.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpSubscribe.java
Labels: documentation, enhancement

#75 feat: 회원가입 페이지 퍼블리싱
  FE/src/App.jsx
  FE/src/pages/SignUp/ParentSignUp.jsx
  FE/src/pages/SignUp/ParentSignUp.module.scss
Labels: enhancement

#79 Feat#40 path
  FE/src/components/Search/AddressFinderMap/AddressFinderMap.jsx
  FE/src/components/Search/Modal.jsx
  FE/src/pages/Search/Search.jsx
  FE/src/pages/Search/Search.module.scss
  FE/src/utils/search.js
Labels: fix, enhancement

#81 Feat#50 subscribe
  BE/iDrop/build.gradle
  BE/iDrop/src/main/java/ifive/idrop/controller/ParentController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/UserController.java
  BE/iDrop/src/main/java/ifive/idrop/dto/BaseResponse.java
  BE/iDrop/src/main/java/ifive/idrop/dto/SubscribeRequest.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Driver.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUp.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpInfo.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpLocation.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpSubscribe.java
  BE/iDrop/src/main/java/ifive/idrop/entity/ReservedSchedule.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/Days.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/ParentRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
  BE/iDrop/src/main/java/ifive/idrop/util/Parser.java
Labels: enhancement

#84 Feat#71 websocket token interceptor
  BE/iDrop/src/main/java/ifive/idrop/entity/Car.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Child.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpInfo.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpLocation.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpSubscribe.java
  BE/iDrop/src/main/java/ifive/idrop/filter/CorsFilter.java
  BE/iDrop/src/main/java/ifive/idrop/filter/JwtAuthorizationFilter.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/PickUpInfoRepository.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/WebSocketConfig.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/WebSocketHandShakeInterceptor.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
Labels: fix

#90 Feat#83 parent socket
  FE/src/components/Map/DriverMap.jsx
  FE/src/components/Map/ParentMap.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.module.scss
  FE/src/constants/constants.js
  FE/src/pages/Location/Location.jsx
  FE/src/service/api.js
Labels: enhancement

#93 Feat#80 search
  FE/src/App.jsx
  FE/src/components/DriverList/DriverListItem.jsx
  FE/src/components/DriverList/DriverListItem.module.scss
  FE/src/components/Search/DayList.jsx
  FE/src/pages/DriverDetail/DriverDetail.jsx
  FE/src/pages/DriverList/DriverList.jsx
  FE/src/pages/Search/Search.jsx
  FE/src/service/api.js
  FE/src/service/mockdata.js
Labels: fix, enhancement

#87 Feat#48 search drivers
  BE/iDrop/.gitignore
  BE/iDrop/build.gradle
  BE/iDrop/src/main/java/ifive/idrop/controller/AuthController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/CommonController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/DriverController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/HomeController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/ParentController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/UserController.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/DriverInformation.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/DriverListRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/LoginRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/SignUpRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/SubscribeRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/TokenRefreshRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/WorkHoursDto.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/BaseResponse.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/DriverDetailResponse.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/DriverListResponse.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/DriverSummary.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/NameResponse.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Child.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Driver.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpInfo.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpSubscribe.java
  BE/iDrop/src/main/java/ifive/idrop/entity/ReservedSchedule.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
  BE/iDrop/src/main/java/ifive/idrop/entity/WorkHours.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/Gender.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/filter/JwtAuthorizationFilter.java
  BE/iDrop/src/main/java/ifive/idrop/filter/VerifyUserFilter.java
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/UserRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
  BE/iDrop/src/main/java/ifive/idrop/service/UserService.java
  BE/iDrop/src/main/java/ifive/idrop/util/RequestSchedule.java
  BE/iDrop/src/main/java/ifive/idrop/util/ScheduleUtils.java
Labels: enhancement

#94 Feat#73 children info api
  FE/src/App.jsx
  FE/src/components/Map/DriverMap.jsx
  FE/src/components/Map/ParentMap.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.module.scss
  FE/src/components/common/Bottomsheet/KidInfoBox.jsx
  FE/src/components/common/Bottomsheet/kidInfoBox.module.scss
  FE/src/hooks/useFetch.js
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/PickUp/PickUp.jsx
  FE/src/service/api.js
Labels: enhancement

#100 Feat#98 separate bottom sheet components
  FE/src/App.jsx
  FE/src/components/Map/DriverMap.jsx
  FE/src/components/Map/ParentMap.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.module.scss
  FE/src/components/common/Bottomsheet/KidInfoBox.jsx
  FE/src/pages/Menu/Menu.jsx
Labels: fix

#102 Feat#78 auth
  FE/src/App.jsx
  FE/src/pages/Login/Login.jsx
  FE/src/utils/auth.js
Labels: enhancement

#104 fix: import useRouteLoaderData
  FE/src/App.jsx
Labels: fix

#106 Feat#103 update search
  FE/src/App.jsx
  FE/src/components/Search/AddressForm.jsx
  FE/src/components/Search/Modal.jsx
  FE/src/components/common/Footer/Footer.jsx
  FE/src/components/common/Footer/Footer.module.scss
  FE/src/pages/Confirmation/Confirmation.jsx
  FE/src/pages/DriverDetail/DriverDetail.jsx
  FE/src/pages/Login/Login.jsx
  FE/src/pages/Search/Search.jsx
  FE/src/utils/auth.js
Labels: fix, enhancement

#105 Feat#101 separate menu page
  FE/src/assets/car.svg
  FE/src/components/Map/DriverMap.jsx
  FE/src/components/Map/ParentMap.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/constants/constants.js
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/SignUp/ParentSignUp.jsx
Labels: fix

#117 fix: OPTIONS 메소드 preflight 허용
  BE/iDrop/src/main/java/ifive/idrop/filter/JwtAuthorizationFilter.java
Labels: fix

#118 Feat#109 pickup image and notes upload
  FE/src/App.jsx
  FE/src/assets/camera.svg
  FE/src/components/Map/DriverMap.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/kidInfoBox.module.scss
  FE/src/components/common/Complete/Complete.jsx
  FE/src/pages/EndPickUp/EndPickUp.jsx
  FE/src/pages/Location/Location.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Menu/menuButton.jsx
  FE/src/pages/PickUp/CameraCapture.jsx
  FE/src/pages/PickUp/CameraCapture.module.scss
  FE/src/pages/PickUp/PickUp.jsx
  FE/src/pages/PickUp/PickUp.module.scss
  FE/src/service/api.js
  FE/src/utils/calculatorDistance.js
Labels: fix, enhancement

#122 Feat#103 update search
  FE/src/App.jsx
  FE/src/components/Search/Modal.jsx
  FE/src/pages/Confirmation/Confirmation.jsx
  FE/src/pages/DriverDetail/DriverDetail.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Onboarding/Onboarding.jsx
  FE/src/pages/Search/Search.jsx
  FE/src/service/api.js
Labels: fix, enhancement

#116 Feat#97 pickup end
  BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUp.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
Labels: enhancement

#110 Feat#99 subscribe info
  BE/iDrop/src/main/java/ifive/idrop/controller/CommonController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/DriverController.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/SubscribeRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/ParentRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
Labels: enhancement

#125 Feat#121 async request add
  FE/src/App.jsx
  FE/src/components/Map/ParentMap.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/KidInfoBox.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Menu/menuButton.jsx
  FE/src/service/api.js
Labels: fix, enhancement

#128 Feat#123 push msg
  FE/package.json
  FE/public/firebase-messaging-sw.js
  FE/src/service/notification/api.js
  FE/src/service/notification/foregroundMessage.js
  FE/src/service/notification/initFirebase.js
  FE/src/service/notification/notificationPermission.js
  FE/src/service/notification/registerServiceWorker.js
  FE/yarn.lock
Labels: enhancement

#126 Feat#112 manage subscribe
  .DS_Store
  BE/.DS_Store
  BE/iDrop/src/main/java/ifive/idrop/controller/DriverController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/ParentController.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/SubscribeCheckRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/DriverSubscribeInfoResponse.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/ParentSubscribeInfoResponse.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpSubscribe.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/PickUpStatus.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
  BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
  BE/iDrop/src/main/java/ifive/idrop/util/RequestSchedule.java
  BE/iDrop/src/main/java/ifive/idrop/util/ScheduleUtils.java
Labels: enhancement

#119 Feat#111 history
  BE/iDrop/src/main/java/ifive/idrop/controller/ParentController.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/CurrentPickUpResponse.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/PickUpInfoStatus.java
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
Labels: enhancement

#133 fix: 빌드 오류 해결
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/ParentRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
Labels: fix

#135 Feat#123 pwa
  FE/index.html
  FE/public/favicon.svg
  FE/public/logo_192.png
  FE/public/logo_512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/service/notification/notificationPermission.js
  FE/src/service/notification/registerServiceWorker.js
Labels: enhancement

#130 Feat#124 naver direction finder
  BE/iDrop/src/main/java/ifive/idrop/websocket/PickUpInfoRepository.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/WebSocketConfig.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/Direction.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionFinder.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionResponse.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/CurrentPickUp.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
  BE/iDrop/src/main/resources/application.yml
Labels: enhancement

#136 Feat#132 subscribe management page
  FE/src/App.jsx
  FE/src/components/Map/DriverMap.jsx
  FE/src/components/Map/ParentMap.jsx
  FE/src/components/common/Bottomsheet/Bottomsheet.jsx
  FE/src/components/common/Bottomsheet/KidInfoBox.jsx
  FE/src/components/common/Bottomsheet/kidInfoBox.module.scss
  FE/src/pages/DriverSubsPage/Management.jsx
  FE/src/pages/DriverSubsPage/Management.module.scss
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Menu/MenuButton.jsx
  FE/src/pages/PickUp/CameraCapture.jsx
  FE/src/pages/PickUp/PickUp.jsx
  FE/src/service/api.js
  FE/src/utils/calculatorDistance.js
Labels: enhancement

#139 feat: 실시간 위치 반영해서 경로 찾기
  BE/iDrop/.gitignore
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionFinder.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/DriverGeoLocation.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/Location.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
Labels: enhancement

#145 Feat#113 subscription history
  FE/src/App.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/Header.module.scss
  FE/src/components/Modal/Modal.jsx
  FE/src/hooks/useFetch.js
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Parents/History/History.jsx
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryDetail.jsx
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryDetail.module.scss
  FE/src/pages/Parents/History/HistoryItem/HistoryItem.jsx
  FE/src/pages/Parents/Subscription/DriverDetail/DriverDetail.jsx
  FE/src/pages/Parents/Subscription/DriverList/DriverList.jsx
  FE/src/service/mockdata.js
  FE/src/service/notification/foregroundMessage.js
  FE/src/service/notification/notificationAPI.js
  FE/src/service/notification/notificationPermission.js
Labels: enhancement

#148 refactor: 컴포넌트 분리
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryCard/CardHeader/CardHeader.jsx
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryCard/CardHeader/CardHeader.module.scss
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryCard/CardMain/CardMain.jsx
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryCard/CardMain/CardMain.module.scss
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryCard/HistoryCard.jsx
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryCard/HistoryCard.module.scss
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryDetail.jsx
  FE/src/pages/Parents/History/HistoryDetailModal/HistoryDetail.module.scss
Labels: refactoring

#146 Feat#141 select pickup child
  FE/src/App.jsx
  FE/src/components/Bottomsheet/Bottomsheet.jsx
  FE/src/components/Bottomsheet/Bottomsheet.module.scss
  FE/src/components/Bottomsheet/ContentsBox/ContentsBox.jsx
  FE/src/components/Bottomsheet/KidInfoBox.jsx
  FE/src/components/Bottomsheet/KidInfoBox/KidInfoBox.jsx
  FE/src/components/Bottomsheet/KidInfoBox/kidInfoBox.module.scss
  FE/src/constants/constants.js
  FE/src/pages/Driver/PickUp/PickUp.jsx
  FE/src/pages/Driver/PickUp/SelectChild/ContentsBox.module.scss
  FE/src/pages/Driver/PickUp/SelectChild/SelectChild.jsx
  FE/src/pages/Driver/PickUp/SelectChild/SelectChild.module.scss
  FE/src/pages/Driver/PickUp/SelectChild/TodayPickUpList.jsx
  FE/src/pages/Driver/SubscriptionManagement/SubscriptionManagement.jsx
  FE/src/pages/Driver/SubscriptionManagement/SubscriptionManagement.module.scss
  FE/src/pages/Map/DriverMap.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Menu/MenuButton/MenuButton.jsx
  FE/src/pages/Menu/MenuButton/menuButton.module.scss
  FE/src/utils/parseData.js
Labels: enhancement

#151 Feat#147 driver today rest of pickup
  BE/iDrop/src/main/java/ifive/idrop/controller/DriverController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/DriverTodayRemainingPickUpResponse.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
Labels: enhancement

#142 Feat#120 push alarm
  .DS_Store
  BE/.DS_Store
  BE/iDrop/.gitignore
  BE/iDrop/build.gradle
  BE/iDrop/src/main/java/ifive/idrop/IDropApplication.java
  BE/iDrop/src/main/java/ifive/idrop/config/FCMConfig.java
  BE/iDrop/src/main/java/ifive/idrop/config/WebConfig.java
  BE/iDrop/src/main/java/ifive/idrop/controller/DriverController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/ParentController.java
  BE/iDrop/src/main/java/ifive/idrop/controller/PickUpController.java
  BE/iDrop/src/main/java/ifive/idrop/dto/request/TokenRequest.java
  BE/iDrop/src/main/java/ifive/idrop/dto/response/PickUpHistoryResponse.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Notification.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUp.java
  BE/iDrop/src/main/java/ifive/idrop/entity/PickUpInfo.java
  BE/iDrop/src/main/java/ifive/idrop/entity/Users.java
  BE/iDrop/src/main/java/ifive/idrop/entity/enums/PickUpInfoStatus.java
  BE/iDrop/src/main/java/ifive/idrop/fcm/AlarmMessage.java
  BE/iDrop/src/main/java/ifive/idrop/fcm/NotificationRequest.java
  BE/iDrop/src/main/java/ifive/idrop/fcm/NotificationUtill.java
  BE/iDrop/src/main/java/ifive/idrop/filter/FCMFilter.java
  BE/iDrop/src/main/java/ifive/idrop/filter/JwtAuthorizationFilter.java
  BE/iDrop/src/main/java/ifive/idrop/repository/DriverRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/NotificationRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/ParentRepository.java
  BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/DriverService.java
  BE/iDrop/src/main/java/ifive/idrop/service/NotificationService.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
  BE/iDrop/src/main/java/ifive/idrop/service/PickUpService.java
  BE/iDrop/src/main/java/ifive/idrop/service/UserService.java
  BE/iDrop/src/main/resources/application.yml
Labels: enhancement

#160 Feat#153 deploy
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  FE/src/App.jsx
  FE/src/components/Bottomsheet/Bottomsheet.jsx
  FE/src/pages/Driver/PickUp/PickUp.jsx
  firebase.json
Labels: enhancement

#158 feat: 부모의 현재 진행 중인 픽업 존재 여부 조회 api
  BE/iDrop/src/main/java/ifive/idrop/controller/ParentController.java
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/repository/PickUpRepository.java
  BE/iDrop/src/main/java/ifive/idrop/service/ParentService.java
Labels: enhancement

#159 Feat#144 parent realtime direction
  BE/iDrop/.gitignore
  BE/iDrop/src/main/java/ifive/idrop/websocket/PickUpInfoRepository.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/WebSocketHandShakeInterceptor.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionFinder.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/dto/Direction.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/dto/NaverDirectionResponse.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/dto/ChildGeoLocation.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/dto/CurrentPickUp.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/dto/DriverGeoLocation.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/dto/Location.java
Labels: enhancement

#168 fix: 네이버 경로 맨앞에 출발지 추가
  BE/iDrop/src/main/java/ifive/idrop/exception/ErrorCode.java
  BE/iDrop/src/main/java/ifive/idrop/filter/CorsFilter.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/NaverDirectionFinder.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/dto/Direction.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/direction/dto/NaverDirectionResponse.java
  BE/iDrop/src/main/java/ifive/idrop/websocket/location/LocationWebSocketHandler.java
  BE/iDrop/src/main/resources/application.yml
Labels: fix

#169 Feat#153 deploy
  FE/index.html
  FE/src/App.jsx
  FE/src/components/Footer/Footer.module.scss
  FE/src/components/Header/Header.module.scss
  FE/src/components/Modal/Modal.jsx
  FE/src/constants/constants.js
  FE/src/pages/Complete/Confirmation/Confirmation.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Parents/Subscription/DriverDetail/DriverDetail.jsx
Labels: enhancement

#166 Feat#162 fix bug error
  FE/src/App.jsx
  FE/src/components/Bottomsheet/Bottomsheet.jsx
  FE/src/components/Bottomsheet/Bottomsheet.module.scss
  FE/src/components/Bottomsheet/KidInfoBox/KidInfoBox.jsx
  FE/src/components/Bottomsheet/KidInfoBox/kidInfoBox.module.scss
  FE/src/components/Layout/Content/EmptyChildData.jsx
  FE/src/components/Layout/Content/NoChildData.module.scss
  FE/src/pages/Driver/PickUp/CameraCapture.jsx
  FE/src/pages/Driver/PickUp/CameraSnapshotPreview.jsx
  FE/src/pages/Driver/PickUp/CameraSnapshotPreview.module.scss
  FE/src/pages/Driver/PickUp/PickUp.jsx
  FE/src/pages/Driver/PickUp/PickUp.module.scss
  FE/src/pages/Driver/SelectChild/ContentsBox.module.scss
  FE/src/pages/Driver/SelectChild/SelectChild.jsx
  FE/src/pages/Driver/SelectChild/SelectChild.module.scss
  FE/src/pages/Driver/SelectChild/TodayPickUpList.jsx
  FE/src/pages/Driver/SubscriptionManagement/SubscriptionManagement.jsx
  FE/src/pages/Driver/SubscriptionManagement/SubscriptionManagement.module.scss
  FE/src/pages/Map/DriverMap.jsx
  FE/src/pages/Map/ParentMap.jsx
  FE/src/pages/Menu/Menu.jsx
  FE/src/pages/Menu/MenuButton/MenuButton.jsx
  FE/src/service/childrenAPI.js
  FE/src/service/driverAPI.js
  FE/src/service/parentsAPI.js
  FE/src/utils/parseData.js
Labels: fix, enhancement
